/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { QuizFactory__factory } from "./QuizFactory__factory";
export { QuizGame__factory } from "./QuizGame__factory";
