/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { QuizFactory } from "./QuizFactory";
export type { QuizGame } from "./QuizGame";
export * as factories from "./factories";
export { QuizFactory__factory } from "./factories/QuizFactory__factory";
export { QuizGame__factory } from "./factories/QuizGame__factory";
