/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface QuizFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "createQuiz" | "getQuizzes" | "quizzes"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createQuiz",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getQuizzes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "quizzes",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "createQuiz", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getQuizzes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "quizzes", data: BytesLike): Result;
}

export interface QuizFactory extends BaseContract {
  connect(runner?: ContractRunner | null): QuizFactory;
  waitForDeployment(): Promise<this>;

  interface: QuizFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createQuiz: TypedContractMethod<
    [question: string, hashedAnswer: BytesLike],
    [void],
    "payable"
  >;

  getQuizzes: TypedContractMethod<[], [string[]], "view">;

  quizzes: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createQuiz"
  ): TypedContractMethod<
    [question: string, hashedAnswer: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getQuizzes"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "quizzes"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  filters: {};
}
